//! Shell completions and the man page are generated by the binary itself, so a
//! packager (Homebrew, a distribution) can produce them without a build step.

use std::process::Command;

fn run(args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_aurora"))
        .args(args)
        .output()
        .unwrap()
}

#[test]
fn completions_are_emitted_for_every_supported_shell() {
    for shell in ["bash", "zsh", "fish", "powershell", "elvish"] {
        let output = run(&["--completions", shell]);
        let stdout = String::from_utf8_lossy(&output.stdout);

        assert!(
            output.status.success(),
            "--completions {shell} must succeed, stderr:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            stdout.contains("aurora"),
            "the {shell} completion script must mention the binary:\n{stdout}"
        );
    }
}

#[test]
fn an_unknown_shell_is_rejected() {
    let output = run(&["--completions", "tcsh"]);
    assert!(
        !output.status.success(),
        "an unsupported shell must be rejected, not silently ignored"
    );
}

#[test]
fn the_man_page_is_emitted_as_roff() {
    let output = run(&["--man"]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(output.status.success(), "--man must succeed");
    assert!(
        stdout.contains(".TH "),
        "the man page must be roff, with a title header:\n{stdout}"
    );
    assert!(
        stdout.contains("Beamfile"),
        "the man page must describe what Aurora runs:\n{stdout}"
    );
}

/// Both are pure emitters: they must not need a Beamfile, since a packager runs
/// them from an arbitrary directory.
#[test]
fn generators_do_not_require_a_beamfile() {
    let dir = tempfile::tempdir().unwrap();

    for args in [["--completions", "bash"], ["--man", ""]] {
        let args: Vec<&str> = args.iter().copied().filter(|a| !a.is_empty()).collect();
        let output = Command::new(env!("CARGO_BIN_EXE_aurora"))
            .args(&args)
            .current_dir(dir.path())
            .output()
            .unwrap();

        assert!(
            output.status.success(),
            "{args:?} must work without a Beamfile, stderr:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
